FORMAT: 1A
HOST: http://apifirst.t-mobile.io/

# tmo-surveys

TMO-Surveys is a simple API allowing consumers create, retrieve, update and delete surveys

## Surveys [/surveys{?limit}]

### List All Surveys [GET]

Returns collection of surveys

+ Parameters
    + limit (number, optional, `10`)
        
+ Response 200 (application/json)

    + Attributes (array[Survey])
    
    + Body

            [{
                "id": "1",
                "title": "API First",
                "description": "This Survey is for API first lunch and learn talk" 
                "questions": [
                    {
                        "text": "Question 1"
                        "choices": [
                            {
                                "text": "choice 1",
                                "votes": 0
                            },
                            {
                                "text": "choice 2",
                                "votes": 0
                            }
                        ]
                    }
                ]
                "created_by": "Ram Gopinathan",
                "create_date": "2015-08-05T08:40:51.620Z"
            }]

            
### Create a New Survey [POST]

You may create your own Survey using this action. It takes a JSON
object containing a Survey and a collection of Questions each with a collection 
of answers in the form of choices.

+ Request (application/json)

    + Attributes (Survey)
    
        {
            "title": "Digital Axioms",
            "description": "This Survey is for Digital Axioms lunch and learn talk" 
            "questions": [
                {
                    "text": "Question 1"
                    "choices": [
                        {
                            "text": "choice 1",
                            "votes": 0
                        },
                        {
                            "text": "choice 2",
                            "votes": 0
                        }
                    ]
                },
                {
                    "text": "Question 2"
                    "choices": [
                        {
                            "text": "choice 1",
                            "votes": 0
                        },
                        {
                            "text": "choice 2",
                            "votes": 0
                        }
                    ]
                }
            ]
            "created_by": "Ram Gopinathan",
            "create_date": "2015-08-05T08:40:51.620Z"
        }

+ Response 201 (application/json)

    + Headers

            Location: /surveys/2

    + Body

            {
                "id": "2",
                "title": "Digital Axioms",
                "description": "This Survey is for Digital Axioms lunch and learn talk" 
                "questions": [
                    {
                        "text": "Question 1"
                        "choices": [
                            {
                                "text": "choice 1",
                                "votes": 0
                            },
                            {
                                "text": "choice 2",
                                "votes": 0
                            }
                        ]
                    },
                    {
                        "text": "Question 2"
                        "choices": [
                            {
                                "text": "choice 1",
                                "votes": 0
                            },
                            {
                                "text": "choice 2",
                                "votes": 0
                            }
                        ]
                    }
                ]
                "created_by": "Ram Gopinathan",
                "create_date": "2015-08-05T08:40:51.620Z"
            }

## Survey [/surveys/{id}]

### Get Survey [GET]

You may get a survey using this action, unique identifier for survey is passed via 
path in URL

+ Parameters
    + id (number, required, `1`)

+ Response 200 (application/json)

    + Attributes (Survey)
    
    + Body
            
            {
                "id": "1",
                "title": "API First",
                "description": "This Survey is for API first lunch and learn talk" 
                "questions": [
                    {
                        "text": "Question 1"
                        "choices": [
                            {
                                "text": "choice 1",
                                "votes": 0
                            },
                            {
                                "text": "choice 2",
                                "votes": 0
                            }
                        ]
                    }
                ]
                "created_by": "Ram Gopinathan",
                "create_date": "2015-08-05T08:40:51.620Z"
            }
    
### Update Survey [PUT]

You may update a survey using this action, it takes a JSON object containing survey
object that was previously retrieved

+ Parameters
    + id (number, required, `1`)

+ Request
    
    + Attributes (Survey)
    
    + Body
    
            {
                "description": "This Survey is for API first lunch and learn talk on March 10th 2017" 
            }
            
+ Response 200 (application/json)

    + Attributes (Survey)

    + Body   
    
            {
                "id": "1",
                "title": "API First",
                "description": "This Survey is for API first lunch and learn talk on March 10th 2017" 
                "questions": [
                    {
                        "text": "Question 1"
                        "choices": [
                            {
                                "text": "choice 1",
                                "votes": 0
                            },
                            {
                                "text": "choice 2",
                                "votes": 0
                            }
                        ]
                    }
                ]
                "created_by": "Ram Gopinathan",
                "create_date": "2015-08-05T08:40:51.620Z"
            }
    
### Delete a survey [DELETE]

You may use this action to delete a survey.

+ Parameters
    + id (number, required, `1`)
    
+ Response 204

# Data Structures

## Survey (object)

- id (number, required)
- title (string, required)
- description (string)
- questions (array[Question], required)
- created_by (string, required)
- create_date (string, required)


## Question (object)

- text (string, required)
- choices (array[Choice], required)

## Choice (object)

- text (string, required)
- votes: `0` (number, required)